config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index


  end

  def show
    @name=params[:name]
    subject=params[:subject]
    subject=params[:subject]
    Prawn::Document.generate(@name+".pdf") do
      text "#{subject}"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
        <%= form_tag   home_show_path,:method => :get do %>
         name: <%= text_field_tag :name, params[:name]%><br>
         subject: <%= text_field_tag :subject, params[:subject] %><br>
           <%=submit_tag '搜索',class: "icon_txt" %>
          <% end %>

app/views/home/show.html.erb
<h1><%=@name %></h1>
<h1><%=@subject %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PDF</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>